### ISSUE TITLE
The application should notify the user if the PDF download fails

### ISSUE THREAD

**Issue by kittytinythai** [DD2480-2021-group-22/jabref#4]
When the application fails to download a file when importing an entry via the JabRef browser extension, then it should notify the user about the failure. The notification should follow the procedure mentioned [here](https://devdocs.jabref.org/getting-into-the-code/code-howtos#outputting-errors-in-the-ui).  

The notification should not contain logs or any technical related messages, just a simple "heads up" about the failure for the user.

**Comment by grundb** [comment]
This is implemented as of 622abb9

**Comment by grundb** [comment]
To clarify, we chose to warn the user when JabRef downloads a PDF file.
