### ISSUE TITLE
Validation of file type of the downloaded file

### ISSUE THREAD

**Issue by kittytinythai** [DD2480-2021-group-22/jabref#5]
If the downloaded file has a specific file type extension (excluding `.html`, `.htm`), then the content should be check so the file is not an HTML document.

**Comment by binsu-kth** [comment]
File can be validated by if (urlDownload.isPdf()) {} , isPdf checks if the MimeType of the object is  "application/pdf".

**Comment by grundb** [comment]
Given the changes in 622abb9, the downloaded file should already have the correct extension (obtained via mime type) and the checking is thus not needed.
